# Generated by Django 5.0.3 on 2024-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen_1', models.ImageField(upload_to='proyectos')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('lenguaje', models.CharField(max_length=50)),
                ('herramientas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
    ]
